INSERT INTO GENRE (GENRE_ID, GENRE_NAME) VALUES (1, 'COMEDY');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME) VALUES (2, 'DRAMA');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME) VALUES (3, 'CARTOON');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME) VALUES (4, 'THRILLER');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME) VALUES (5, 'DOCUMENTARY');
INSERT INTO GENRE (GENRE_ID, GENRE_NAME) VALUES (6, 'ACTION');

INSERT INTO RATING (RATING_ID, RATING_NAME) VALUES (1, 'G');
INSERT INTO RATING (RATING_ID, RATING_NAME) VALUES (2, 'PG');
INSERT INTO RATING (RATING_ID, RATING_NAME) VALUES (3, 'PG13');
INSERT INTO RATING (RATING_ID, RATING_NAME) VALUES (4, 'R');
INSERT INTO RATING (RATING_ID, RATING_NAME) VALUES (5, 'NC17');